ARG BASE_IMAGE=livepeer/ai-runner:live-base
FROM ${BASE_IMAGE}

# Install Miniconda and create the 'comfystream' environment
ARG PYTHON_VERSION=3.11
ENV CONDA_DIR="/workspace/miniconda3"
ENV PATH="$CONDA_DIR/bin:$PATH" \
    PIP_PREFER_BINARY=1

RUN apt update && apt install -yqq --no-install-recommends wget curl ca-certificates && \
    wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py310_23.11.0-2-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p $CONDA_DIR && \
    rm ~/miniconda.sh && \
    conda init bash && \
    conda config --set auto_activate_base false && \
    conda clean -a -y && \
    conda create -n comfystream python=$PYTHON_VERSION -y && \
    conda run -n comfystream pip install --no-cache-dir --upgrade pip==23.3.2 setuptools==69.5.1 wheel==0.43.0 && \
    conda clean -a -y && \
    apt purge -y --auto-remove wget curl && \
    apt clean && rm -rf /var/lib/apt/lists/*

# Install StreamDiffusion dependencies into the comfystream environment
RUN conda run -n comfystream pip install --no-cache-dir --force-reinstall \
    torch==2.7.1+cu128 \
    torchvision==0.22.1+cu128 \
    torchaudio==2.7.1+cu128 \
    --index-url https://download.pytorch.org/whl/cu128

# Install StreamDiffusion lib into the comfystream environment
ARG STREAMDIFFUSION_VERSION=v1.0.0-beta
RUN conda run -n comfystream pip install git+https://github.com/daydreamlive/StreamDiffusion.git@${STREAMDIFFUSION_VERSION}#egg=streamdiffusion[tensorrt,controlnet,ipadapter]

# Install TensorRT bindings and libraries into the comfystream environment
RUN conda run -n comfystream python -m streamdiffusion.tools.install-tensorrt

WORKDIR /app

# Disable HF hub connectivity to avoid internet access during runtime.
# This is manually disabled on the script to download models (dl_checkpoints.sh)
ENV HF_HUB_OFFLINE=1

# Create symlink for where StreamDiffusion builds TensorRT engines at runtime
RUN ln -s /models/StreamDiffusion--engines ./engines
# this is required for faceid ipadapter, whose dependency instals on a fixed path
RUN mkdir -p /root && ln -s /models/insightface /root/.insightface
# this one is used only for realesrgan_trt which has ./models hardcoded
RUN ln -s /models/StreamDiffusion--models ./models
